title: Age of Berk Add-on
description: 

remote_theme: jekyll/minima

minima:
  skin: "dark"
  date_format: "%b %d, %y"
  social_links:
    
header_pages:
    - index.md
    - downloads.md
    - info.md
    - faq.md
    - about_us.md
  
google_analytics: G-KPDDEY2P5Z
